### ISSUE TITLE
Pinmapping in code different from description

### ISSUE THREAD

**Issue by timothy3001** [ardyesp/ESPWebDAV#1]
Hi there,

I have two questions actually: 

1. In the hookup guide it says the CS Pin of the microsd should be connected to GPIO15. In the code, the fields "CS_SENSE" and "SD_CS" are mapped to pin 5 and 4. I actually did hook up the CS of the sd card to pin 5 now, because pin 15 needs to be low at startup if i remember correctly.

2. I only attached one pin to the CS pin though. But in the code there are two pins used for CS pin of the sdcard. One for communication and i guess the other to sense if there's some action going on already with the sdcard. I probably need to hookup pin 4 AND 5 to the sd cards's CS pin, am I right?

And thanks for the project! When I can get it to work, its gonna be a blast and will support my laziness a lot!

Greetings
Timo

**Comment by ardyesp** [comment]
Fixed the diagram and readme to reflect the CS pinouts. Thanks.
