### ISSUE TITLE
Static IP

### ISSUE THREAD

**Issue by acguardia** [ardyesp/ESPWebDAV#15]
Can I configure a static IP directly in the firmware?
Because I don't have access to wifi router to fix IP by MAC from SD-WiFi module.

**Comment by ardyesp** [comment]
Yes, when you initialize the WiFi, you can pass in the static IP address there - 
```WiFi.config(staticIP, subnet, gateway, dns);```
See the [documentation](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.h) on how to use it.
