### ISSUE TITLE
SD card speed

### ISSUE THREAD

**Issue by set4up** [ardyesp/ESPWebDAV#2]
Hello. Can I somehow increase the speed of work with the SD card? Now I have a speed of approximately 176kb / s.

**Comment by ardyesp** [comment]
The speed is limited by amount of RAM available in ESP8266. You can try port it over to ESP32 to get better results.

**Comment by set4up** [comment]
The speed now worries me less, I had another problem: over time, not all of the file was first written, and then it completely stopped writing.

**Comment by ardyesp** [comment]
It’s been working flawlessly for me. I would say check the wiring for loose connection or maybe a new SD card. 
You can check SDFat library examples and try to read/write directly, without WiFi connection.

**Comment by set4up** [comment]
Good idea. thank


>Воскресенье, 27 января 2019, 18:19 +03:00 от ardyesp <notifications@github.com>:
>
>Это работает безупречно для меня.  Я бы сказал, проверьте проводку на предмет слабого соединения или, может быть, новую SD-карту. 
>Вы можете проверить примеры библиотек SDFat и попробовать читать / писать напрямую, без подключения к WiFi. 
>
>
>> 27 января 2019 года, в 3:12, set4up <  notifications@github.com > wrote: 
>>> 
>Скорость теперь беспокоит меня меньше, у меня возникла другая проблема: со временем не весь файл был впервые написан, и тогда это полностью прекратило писать. 
>>> 
>- 
>> Вы получаете это, потому что вы прокомментировали. 
>> Ответьте на это письмо напрямую, просмотрите его на GitHub или отключите тему.
>- 
>Вы получаете это, потому что вы автор темы. 
>Ответьте на это письмо напрямую,  просмотрите его на GitHub или  отключите тему .

С уважением, Евгений
